# Generated by Django 6.0.5 on 2026-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='abroad_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='abroad_industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='abroad_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='abroad_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certification',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current CTC in LPA', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('7th', '7th Standard'), ('8th', '8th Standard'), ('9th', '9th Standard'), ('10th', '10th / SSLC'), ('11th', '11th Standard'), ('12th', '12th / HSC / PUC'), ('iti', 'ITI'), ('diploma', 'Diploma'), ('ug', 'Under-Graduate / Degree'), ('pg', 'Post-Graduate')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected CTC in LPA', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_abroad_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('it_software', 'IT / Software'), ('healthcare', 'Healthcare & Pharma'), ('construction', 'Construction & Real Estate'), ('retail', 'Retail & FMCG'), ('hospitality', 'Hospitality & Tourism'), ('education', 'Education & Training'), ('finance', 'Finance, Banking & Insurance'), ('agriculture', 'Agriculture & Food Processing'), ('logistics', 'Logistics & Transportation'), ('automobile', 'Automobile & Engineering'), ('textile', 'Textile & Garments'), ('oil_gas', 'Oil, Gas & Energy'), ('government', 'Government / PSU'), ('media', 'Media & Entertainment'), ('telecom', 'Telecom'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iti_diploma_specialization',
            field=models.CharField(blank=True, help_text='Specialization — for ITI / Diploma only', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages_known',
            field=models.CharField(blank=True, help_text='Comma-separated, e.g. Telugu, Hindi, English', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passed_out_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
