# Generated by Django 6.0.5 on 2026-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='higher_education_degree',
            field=models.CharField(blank=True, help_text='Degree name — for UG / PG, e.g. B.Tech, MBA, B.Com, M.Sc', max_length=200),
        ),
    ]
