# Generated by Django 6.0.5 on 2026-07-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_higher_education_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_level_2',
            field=models.CharField(blank=True, choices=[('7th', '7th Standard'), ('8th', '8th Standard'), ('9th', '9th Standard'), ('10th', '10th / SSLC'), ('11th', '11th Standard'), ('12th', '12th / HSC / PUC'), ('iti', 'ITI'), ('diploma', 'Diploma'), ('ug', 'Under-Graduate / Degree'), ('pg', 'Post-Graduate')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='higher_education_degree_2',
            field=models.CharField(blank=True, help_text='Degree name — for UG / PG (2nd entry), e.g. MBA, M.Tech', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iti_diploma_specialization_2',
            field=models.CharField(blank=True, help_text='Specialization — for ITI / Diploma (2nd entry)', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passed_out_year_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
