# Generated by Django 6.0.5 on 2026-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_secondary_education_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company Name', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_person_email',
            field=models.EmailField(blank=True, help_text='Manager / HR Email ID', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_person_mobile',
            field=models.CharField(blank=True, help_text='Manager / HR Mobile Number', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_person_role',
            field=models.CharField(blank=True, help_text='Manager / HR Role', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
    ]
