# Generated by Django 6.0.5 on 2026-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_experience_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='english_proficiency',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gujarati_proficiency',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hindi_proficiency',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telugu_proficiency',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages_known',
            field=models.CharField(blank=True, help_text='Comma-separated summary of languages known', max_length=300),
        ),
    ]
