# Generated by Django 6.0.5 on 2026-07-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_language_proficiency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Pro subscription status'),
        ),
    ]
