# Generated by Django 6.0.5 on 2026-07-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free Plan'), ('normal', 'Normal User'), ('pro', 'Pro User')], default='free', help_text='Subscription plan type', max_length=20),
        ),
    ]
