# Generated by Django 6.0.5 on 2026-07-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Candidate resume (PDF / DOC / DOCX)', null=True, upload_to='resumes/'),
        ),
    ]
