# Generated by Django 6.0.5 on 2026-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Extracted text of the uploaded resume — used for accurate candidate search'),
        ),
    ]
