# Generated by Django 6.0.5 on 2026-07-30 19:16

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_resume_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Candidate resume (PDF / DOC / DOCX)', null=True, storage=users.models.OverwriteStorage(), upload_to=users.models.resume_upload_path),
        ),
    ]
