# Generated by Django 6.0.7 on 2026-08-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_educations_json',
            field=models.JSONField(blank=True, default=list, help_text='Stores an array of additional education records as JSON', null=True),
        ),
    ]
