# Generated by Django 5.2.17 on 2026-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_subscription_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_expiry_notice',
            field=models.BooleanField(default=False, help_text='Set when a paid plan auto-lapsed to Free; drives the one-time "plan expired" popup'),
        ),
    ]
