# Generated by Django 6.0.7 on 2026-08-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_backfill_subscription_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alternate_mobile',
            field=models.CharField(blank=True, help_text='Stored in E.164 format, e.g. +919876543210', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Stored in E.164 format, e.g. +919876543210', max_length=20),
        ),
    ]
