# Generated by Django 6.0.7 on 2026-08-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userprofile_alternate_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_person_mobile',
            field=models.CharField(blank=True, help_text='Manager / HR Mobile Number, stored in E.164 format, e.g. +919876543210', max_length=20),
        ),
    ]
