# Generated by Django 5.2.17 on 2026-09-01 14:30

import core.crypto_fields
from django.db import migrations


def encrypt_existing_identity_numbers(apps, schema_editor):
    """Existing rows were written as plaintext under the old CharField. Once
    the AlterField above has run, EncryptedCharField.from_db_value() will try
    to Fernet-decrypt that plaintext, fail, and fall back to returning it
    as-is — so a plain re-save round-trips each value through
    get_prep_value() and encrypts it for the first time."""
    UserProfile = apps.get_model('users', 'UserProfile')
    fields = ('aadhar_number', 'pan_number', 'passport_number')
    for profile in UserProfile.objects.all().iterator():
        if any(getattr(profile, f) for f in fields):
            profile.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_userprofile_contact_person_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_number',
            field=core.crypto_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pan_number',
            field=core.crypto_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=core.crypto_fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.RunPython(encrypt_existing_identity_numbers, migrations.RunPython.noop),
    ]
