# Generated by Django 5.2.17 on 2026-09-04 12:02

import django.db.models.deletion
import skillup_assessment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('english_vocab', 'English & Vocab'), ('aptitude', 'Aptitude'), ('tech', 'Tech')], db_index=True, max_length=20)),
                ('certificate_name', models.CharField(max_length=150)),
                ('score', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField(default=100)),
                ('certificate_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=skillup_assessment.models.certificate_pdf_path)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillup_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='one_certificate_per_user_per_module')],
            },
        ),
    ]
