# Generated by Django 6.0.5 on 2026-05-13 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('gd', 'Group Discussion'), ('jam', 'JAM'), ('roleplay', 'Role Play'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('listening', 'Listening'), ('reading', 'Reading')], max_length=20)),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=25)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
