# Generated by Django 6.0.2 on 2026-05-06 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('speaking', 'Speaking & Presentation'), ('writing', 'Writing & Correspondence'), ('vocabulary', 'Vocabulary & Idioms'), ('negotiation', 'Negotiation & Meetings'), ('communication', 'Professional Communication'), ('analysis', 'Analysis & Reporting')], max_length=50)),
                ('level', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('materials', models.TextField()),
                ('objective', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-book', max_length=100)),
                ('color_class', models.CharField(default='primary', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exercise_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('bingo', 'Vocabulary Bingo'), ('writing', 'Writing Submission'), ('timer', 'Timed Activity')], max_length=30)),
                ('instructions', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_cards', to='activities.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=300)),
                ('option_b', models.CharField(blank=True, max_length=300)),
                ('option_c', models.CharField(blank=True, max_length=300)),
                ('option_d', models.CharField(blank=True, max_length=300)),
                ('correct_answer', models.CharField(max_length=300)),
                ('explanation', models.TextField(blank=True)),
                ('left_item', models.CharField(blank=True, max_length=200)),
                ('right_item', models.CharField(blank=True, max_length=200)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.exercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subactivities', to='activities.activity')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('activity', 'order')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='sub_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='activities.subactivity'),
        ),
        migrations.CreateModel(
            name='UserExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('answers_json', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sub_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.subactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sub_activity')},
            },
        ),
    ]
