# Generated by Django 6.0.5 on 2026-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('speaking', 'Speaking & Presentation'), ('writing', 'Writing & Correspondence'), ('vocabulary', 'Vocabulary & Idioms'), ('negotiation', 'Negotiation & Meetings'), ('communication', 'Professional Communication'), ('analysis', 'Analysis & Reporting'), ('workshop', 'Interactive Workshop')], max_length=50),
        ),
    ]
