# Generated by Django 6.0.7 on 2026-08-05 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeActivitySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_selections', to='activities.activity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_activity_selection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
