# Generated by Django 5.2.17 on 2026-08-25 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_userexerciseresult_result_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeactivityselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_activity_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='freeactivityselection',
            constraint=models.UniqueConstraint(fields=('user', 'activity'), name='unique_free_activity_selection'),
        ),
    ]
