# Generated by Django 6.0.5 on 2026-06-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_seeded',
            field=models.BooleanField(default=False, help_text='True if this job was seeded from job_photos directory'),
        ),
    ]
