# Generated by Django 6.0.5 on 2026-06-14 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_jobposting_is_seeded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_user',
            field=models.ForeignKey(blank=True, help_text='Student user who applied via resume parsing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct Apply'), ('resume_parsed', 'Resume Parsed')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
