# Generated by Django 6.0.5 on 2026-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0003_jobapplication_applicant_user_jobapplication_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_gst',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_pan_tin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='hr_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='hr_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
