# Generated by Django 6.0.5 on 2026-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0004_employer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('walk_in', 'Walk In'), ('virtual', 'Virtual'), ('others', 'Others')], default='virtual', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interview_mode_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='notice_period',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('15_days', '15 Days'), ('30_days', '30 Days')], default='immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_environment',
            field=models.CharField(blank=True, choices=[('wfh', 'Work From Home'), ('hybrid', 'Hybrid'), ('wfo', 'Work From Office')], default='wfo', max_length=10),
        ),
    ]
