# Generated by Django 6.0.5 on 2026-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0005_add_job_posting_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='notice_period_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='notice_period',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('others', 'Others')], default='immediate', max_length=10),
        ),
    ]
