# Generated by Django 6.0.7 on 2026-08-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0007_seed_jobs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='hr_contact',
            field=models.CharField(blank=True, help_text='Stored in E.164 format, e.g. +919876543210', max_length=20),
        ),
    ]
