# Generated by Django 5.2.17 on 2026-09-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0013_alter_resumeinterviewsession_interview_video'),
        ('jobs_app', '0008_alter_employerprofile_hr_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='career_app.resumeinterviewsession'),
        ),
    ]
