# Generated by Django 5.2.17 on 2026-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0009_jobapplication_interview_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='last_notified_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
