# Generated by Django 5.2.17 on 2026-09-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0010_jobapplication_last_notified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary_format',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('lpa', 'LPA (Lakhs Per Annum)')], default='monthly', max_length=10),
        ),
    ]
