# Generated by Django 5.2.17 on 2026-09-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0011_jobposting_salary_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('1-2', '1-2 Years'), ('3-5', '3-5 Years'), ('5-8', '5-8 Years'), ('8+', '8+ Years'), ('custom', 'Enter manually')], max_length=20),
        ),
    ]
