# Generated by Django 5.2.17 on 2026-09-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0012_jobposting_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='contract_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
