# Generated by Django 5.2.17 on 2026-09-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0013_jobposting_contract_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='education',
            field=models.CharField(blank=True, choices=[('below_10th', 'Below 10th'), ('10th', '10th'), ('12th', '12th'), ('degree_ug', 'Degree/UG'), ('masters_pg', 'Masters/PG'), ('custom', 'Enter manually')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='education_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
