# Generated by Django 5.2.17 on 2026-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0014_jobposting_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='education',
            field=models.CharField(blank=True, choices=[('7th', '7th Standard'), ('8th', '8th Standard'), ('9th', '9th Standard'), ('10th', '10th / SSLC'), ('11th', '11th Standard'), ('12th', '12th / HSC / PUC'), ('iti', 'ITI'), ('diploma', 'Diploma'), ('ug', 'Under-Graduate / Degree'), ('pg', 'Post-Graduate'), ('custom', 'Enter manually')], max_length=20),
        ),
    ]
