# Generated by Django 5.2.17 on 2026-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0016_jobposting_education_below_10th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
