# Generated by Django 5.2.17 on 2026-09-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0017_jobposting_requirements_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='perks',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
