# Generated by Django 5.2.17 on 2026-09-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0018_jobposting_perks'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='mandatory_skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
