# Generated by Django 5.2.17 on 2026-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0019_jobposting_mandatory_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='experience_plus',
            field=models.BooleanField(default=False),
        ),
    ]
