# Generated by Django 5.2.17 on 2026-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0020_jobposting_experience_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='skills_required',
            field=models.CharField(blank=True, help_text='Comma separated skills', max_length=500),
        ),
    ]
