# Generated by Django 5.2.17 on 2026-09-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0021_jobposting_skills_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_category',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('non_it', 'Non-IT')], max_length=10),
        ),
    ]
