# Generated by Django 5.2.17 on 2026-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0022_jobposting_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_classification',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('non_technical', 'Non-Technical')], max_length=15),
        ),
    ]
