# Generated by Django 5.2.17 on 2026-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0023_jobposting_job_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='experience_years_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
