# Generated by Django 5.2.17 on 2026-09-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0024_jobposting_experience_years_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering Skills'), ('epc_construction', 'EPC & Construction Skills'), ('hse_safety', 'HSE / EHS / Safety Skills'), ('fire_emergency', 'Fire & Emergency Skills'), ('quality_inspection', 'Quality & Inspection Skills'), ('plant_operations', 'Plant Operations & Maintenance'), ('renewable_energy', 'Renewable Energy Skills'), ('industrial_manufacturing', 'Industrial & Manufacturing Skills'), ('automotive_ev', 'Automotive & EV Skills'), ('oil_gas_energy', 'Oil & Gas / Energy Skills'), ('logistics_workforce', 'Logistics & Industrial Workforce Skills')], max_length=30),
        ),
    ]
