# Generated by Django 5.2.17 on 2026-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0026_jobposting_department_skilled_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='designation',
            field=models.CharField(blank=True, choices=[('Technical', [('manager', 'Manager'), ('project_engineer', 'Project Engineer'), ('site_engineer', 'Site Engineer'), ('estimation_engineer', 'Estimation Engineer'), ('back_office_manager', 'Back Office Manager'), ('project_coordinator', 'Project Coordinator'), ('project_director', 'Project Director')]), ('Non-Technical', [('hr_manager', 'HR Manager'), ('hr_executive', 'HR Executive'), ('hr_recruiter', 'HR Recruiter'), ('back_office_executive', 'Back Office Executive'), ('accountant', 'Accountant'), ('account_executive', 'Account Executive'), ('sales_executive', 'Sales Executive'), ('sales_manager', 'Sales Manager'), ('sales_officer', 'Sales Officer'), ('sales_marketing_executive', 'Sales & Marketing Executive'), ('store_executive', 'Store Executive'), ('store_supervisor', 'Store Supervisor'), ('store_manager', 'Store Manager'), ('purchase_executive', 'Purchase Executive'), ('purchase_manager', 'Purchase Manager')])], max_length=30),
        ),
    ]
