# Generated by Django 5.2.17 on 2026-09-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0027_jobposting_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='age_limit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='application_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='certifications',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='industry_experience',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='industry_sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
