# Generated by Django 5.2.17 on 2026-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0028_jobposting_non_it_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='language_requirements',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='software_skills',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
