# Generated by Django 5.2.17 on 2026-09-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0029_jobposting_non_it_non_technical_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='department_function',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='functional_skills',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
