# Generated by Django 5.2.17 on 2026-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0030_jobposting_non_technical_department_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='education',
            field=models.CharField(blank=True, choices=[('below_10th', 'Below 10th Standard'), ('10th', '10th / SSLC'), ('11th', '11th Standard'), ('12th', '12th / HSC / PUC'), ('iti', 'ITI'), ('diploma', 'Diploma'), ('ug', 'Under-Graduate / Degree'), ('pg', 'Post-Graduate'), ('degree', 'Degree'), ('certification', 'Certification'), ('custom', 'Enter manually')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('permanent', 'Permanent'), ('project', 'Project')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='work_environment',
            field=models.CharField(blank=True, choices=[('wfh', 'Work From Home'), ('hybrid', 'Hybrid'), ('wfo', 'Work From Office'), ('onsite', 'On-site'), ('field', 'Field'), ('plant', 'Plant'), ('office', 'Office')], default='wfo', max_length=10),
        ),
    ]
