# Generated by Django 5.2.17 on 2026-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0031_jobposting_non_it_technical_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='notice_period',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('others', 'Others'), ('notice_ok', 'Notice period acceptable')], default='immediate', max_length=10),
        ),
    ]
