# Generated by Django 6.0.5 on 2026-05-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumequestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
