# Generated by Django 6.0.5 on 2026-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0002_resumequestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeinterviewsession',
            name='is_passed',
            field=models.BooleanField(default=False, help_text='True if total_score >= 70'),
        ),
        migrations.AddField(
            model_name='resumeinterviewsession',
            name='total_score',
            field=models.IntegerField(blank=True, help_text='Total scaled integer score out of 100', null=True),
        ),
        migrations.AddField(
            model_name='resumequestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
    ]
