# Generated by Django 6.0.7 on 2026-08-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0003_resumeinterviewsession_is_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumequestion',
            name='question_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('coding', 'Coding')], default='theory', max_length=20),
        ),
    ]
