# Generated by Django 5.2.17 on 2026-08-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0005_razorpaypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
        ),
        migrations.AddField(
            model_name='razorpaypayment',
            name='refunded_amount_paise',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='razorpaypayment',
            name='status',
            field=models.CharField(choices=[('captured', 'Captured'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded'), ('refund_required', 'Refund required — captured but not applied')], default='captured', max_length=32),
        ),
        migrations.AddField(
            model_name='razorpaypayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='razorpaypayment',
            name='razorpay_order_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
