# Generated by Django 5.2.17 on 2026-08-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0006_payment_status_and_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
