# Generated by Django 5.2.17 on 2026-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0007_razorpaypayment_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeinterviewsession',
            name='experience_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]