# Generated by Django 5.2.17 on 2026-09-07 10:20

import career_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0008_resumeinterviewsession_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeinterviewsession',
            name='camera_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeinterviewsession',
            name='interview_video',
            field=models.FileField(blank=True, null=True, upload_to=career_app.models.interview_video_upload_path),
        ),
    ]
