# Generated by Django 5.2.17 on 2026-09-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0009_resumeinterviewsession_camera_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanswer',
            name='timed_out',
            field=models.BooleanField(default=False, help_text='Answer was auto-submitted because the 30s timer expired'),
        ),
        migrations.AddField(
            model_name='resumequestion',
            name='presented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
