# Generated by Django 5.2.17 on 2026-09-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0010_answer_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeinterviewsession',
            name='malpractice_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged for review'), ('terminated', 'Terminated')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeinterviewsession',
            name='malpractice_violation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InterviewViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('FACE_NOT_DETECTED', 'Face not detected'), ('MULTIPLE_FACES', 'Multiple faces detected'), ('TAB_SWITCH', 'Tab switch'), ('WINDOW_BLUR', 'Window/focus change'), ('CAMERA_INTERRUPTED', 'Camera interrupted'), ('FULLSCREEN_EXIT', 'Fullscreen exit')], max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('occurrence_number', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='career_app.resumeinterviewsession')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
