# Generated by Django 5.2.17 on 2026-09-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0011_anti_malpractice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewviolation',
            name='violation_type',
            field=models.CharField(choices=[('FACE_NOT_DETECTED', 'Face not detected'), ('MULTIPLE_FACES', 'Multiple faces detected'), ('TAB_SWITCH', 'Tab switch'), ('WINDOW_BLUR', 'Window/focus change'), ('CAMERA_INTERRUPTED', 'Camera interrupted'), ('FULLSCREEN_EXIT', 'Fullscreen exit'), ('COPY_PASTE', 'Copy/cut/paste detected'), ('SCREENSHOT_ATTEMPT', 'Screenshot attempt detected')], max_length=32),
        ),
    ]
