# Generated by Django 5.2.17 on 2026-09-15 16:02

import career_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0012_alter_interviewviolation_violation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeinterviewsession',
            name='interview_video',
            field=models.FileField(blank=True, null=True, storage=career_app.models.interview_video_storage, upload_to=career_app.models.interview_video_upload_path),
        ),
    ]
