# Generated by Django 5.2.17 on 2026-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0013_alter_resumeinterviewsession_interview_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='industry',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
