# Generated by Django 5.2.17 on 2026-10-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0015_backfill_blank_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeRoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Matches a built-in role (e.g. "project-manager") or names a new one.', max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('it', 'IT'), ('tech', 'Non-IT · Technical'), ('nt', 'Non-IT · Non-Technical')], max_length=10)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(choices=[('code', 'code'), ('chart', 'chart'), ('brain', 'brain'), ('layers', 'layers'), ('bug', 'bug'), ('globe', 'globe'), ('net', 'net'), ('shield', 'shield'), ('flag', 'flag'), ('gear', 'gear'), ('hat', 'hat'), ('calc', 'calc'), ('clip', 'clip'), ('people', 'people'), ('crown', 'crown'), ('search', 'search'), ('brief', 'brief'), ('trend', 'trend'), ('box', 'box'), ('cart', 'cart'), ('wallet', 'wallet'), ('mega', 'mega'), ('bolt', 'bolt')], default='brief', max_length=20)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, help_text='One item per line. Leave blank to keep the built-in value.')),
                ('required_skills', models.TextField(blank=True, help_text='One item per line. Leave blank to keep the built-in value.')),
                ('recommended_skills', models.TextField(blank=True, help_text='One item per line. Leave blank to keep the built-in value.')),
                ('career_path', models.TextField(blank=True, help_text='One item per line. Leave blank to keep the built-in value.')),
                ('certifications', models.TextField(blank=True, help_text='One item per line. Leave blank to keep the built-in value.')),
                ('experience_label', models.CharField(blank=True, help_text='Heading for the employment section, e.g. "Site Experience".', max_length=60)),
                ('role_fields', models.JSONField(blank=True, default=list, help_text='Role-specific form fields: [{"label": "Project planning", "options": ["Scheduling", "WBS"]}, …]')),
                ('level_suggestions', models.JSONField(blank=True, default=dict, help_text='Per experience level ("fresher", "1-3", "3-5", "5+"): {"skills": [...], "responsibilities": [...], "projects": [...], "training": [...]}')),
                ('summary_templates', models.JSONField(blank=True, default=dict, help_text='Per experience level: a list of editable summary templates. Use [placeholders] for anything the candidate must fill in.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='0 keeps the built-in position.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume builder role',
                'verbose_name_plural': 'Resume builder roles',
                'ordering': ('display_order', 'title'),
            },
        ),
    ]
