# Generated by Django 5.2.18 on 2026-10-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0017_resume_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeinterviewsession',
            name='target_role',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
