# Generated by Django 6.0.7 on 2026-08-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_app', '0002_add_sample_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamsession',
            name='language',
            field=models.CharField(blank=True, default='english', help_text='Language chosen in the header dropdown when the session was recorded. Feedback is generated in this language.', max_length=20),
        ),
    ]
